### PR TITLE
Update spawn_defs_robots.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
You also need to add count + kills + color here for new units https://github.com/n3wm1nd/Robot-Defense/blob/master/luaui/widgets/gui_chicken.lua

**Comment by nixtux** [comment]
Cant merge

**Comment by skymyj** [comment]
Conflicts Now.. 
Nix : "you also need to add count + kills + color here for new units" => was on other request

**Comment by skymyj** [comment]
I'm giving up

**Comment by nixtux** [comment]
Skymyj lol it would not merge because it was already merged and didn't show it

**Comment by skymyj** [comment]
good :)

**Pull request closed without merging**
